const Menu = [
    {
        id: 0,
        name: "Mehran",
        category: "lunch",
        image: "img/cu2.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 1,
        name: "Mehran_1",
        category: "evening",
        image: "img/cu3.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 2,
        name: "Mehran_2",
        category: "breakfast",
        image: "img/cu4.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 3,
        name: "Mehran_3",
        category: "lunch",
        image: "img/d6.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 4,
        name: "Mehran_4",
        category: "dinner",
        image: "img/d7.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 5,
        name: "Mehran_5",
        category: "dinner",
        image: "img/d8.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 6,
        name: "Mehran_6",
        category: "evening",
        image: "img/f2.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 7,
        name: "Mehran_6",
        category: "lunch",
        image: "img/f3.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 8,
        name: "Mehran_7",
        category: "breakfast",
        image: "img/f4.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 9,
        name: "Mehran_9",
        category: "breakfast",
        image: "img/i1.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 10,
        name: "Mehran_10",
        category: "breakfast",
        image: "img/i2.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 11,
        name: "Mehran_11",
        category: "lunch",
        image: "img/i3.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 12,
        name: "Mehran_12",
        category: "lunch",
        image: "img/i7.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 13,
        name: "Mehran_13",
        category: "evening",
        image: "img/pic-1.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 14,
        name: "Mehran_14",
        category: "dinner",
        image: "img/pic-3.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 15,
        name: "Mehran_15",
        category: "lunch",
        image: "img/pic-5.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 16,
        name: "Mehran_16",
        category: "breakfast",
        image: "img/r1.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 17,
        name: "Mehran_17",
        category: "breakfast",
        image: "img/r2.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 18,
        name: "Mehran_18",
        category: "lunch",
        image: "img/r5.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
    {
        id: 18,
        name: "Mehran_180",
        category: "samosa",
        image: "img/r5.png",
        price: 25,
        description: "Food is Love when Eat Properly",
    },
];
export default Menu;
